# Generated by Django 5.2.3 on 2025-06-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreF2M', '0001_initial'),
    ]

    operations = [
    ]
