# Generated by Django 5.2.3 on 2025-06-26 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreF2M', '0003_systemconfiguration_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('super_admin', 'Super Administrator'), ('user_manager', 'User Manager'), ('transaction_manager', 'Transaction Manager'), ('content_moderator', 'Content Moderator'), ('analytics_viewer', 'Analytics Viewer'), ('support_agent', 'Support Agent')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('permissions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_roles',
            },
        ),
        migrations.CreateModel(
            name='AdminRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(limit_choices_to={'user_type': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'user_type': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreF2M.adminrole')),
            ],
            options={
                'db_table': 'admin_role_assignments',
                'unique_together': {('admin_user', 'role')},
            },
        ),
    ]
